[[headers]]
  for = "/Build/*.js.br"
  [headers.values]
  Content-Type = "application/javascript"
  Content-Encoding = "br"
  Cache-Control = "no-store"

[[headers]]
  for = "/Build/*.wasm.br"
  [headers.values]
  Content-Type = "application/wasm"
  Content-Encoding = "br"
  Cache-Control = "no-store"

[[headers]]
  for = "/Build/*.data.br"
  [headers.values]
  Content-Type = "application/octet-stream"
  Content-Encoding = "br"
  Cache-Control = "no-store"

[[headers]]
  for = "/Build/*.loader.js"
  [headers.values]
  Content-Type = "application/javascript"
  Cache-Control = "no-store"

[[headers]]
  for = "/aa/*.json"
  [headers.values]
  Content-Type = "application/json; charset=utf-8"
  Cache-Control = "no-cache"

[[headers]]
  for = "/aa/*.hash"
  [headers.values]
  Content-Type = "text/plain; charset=utf-8"
  Cache-Control = "no-cache"

[[headers]]
  for = "/aa/*.bundle"
  [headers.values]
  Content-Type = "application/octet-stream"
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/aa/*"
  [headers.values]
  Access-Control-Allow-Origin = "*"
  Access-Control-Allow-Methods = "GET, HEAD, OPTIONS"
  Access-Control-Allow-Headers = "*"